global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;
global using Notiflow.Backoffice.Domain.Entities.Users;
global using Notiflow.IdentityServer.Core.Entities.Tenants;
global using Notiflow.IdentityServer.Infrastructure.Data;
global using Puzzle.Lib.Database.IOC;
global using Puzzle.Lib.Entities.Entities.Historical;
global using System.Reflection;
