version: "3.8"

services:
  identityserver.mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
  backoffice.postgresql:
    image: postgres
  backoffice.rabbitmq.1:
    image: rabbitmq:3.11.20-management
  backoffice.rabbitmq.2:
    image: rabbitmq:3.11.20-management
  projections.rabbitmq:
    image: rabbitmq:3.11.20-management
  redis-master:
    image: redis:latest
  redis-slave:
    image: redis:latest
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
  kibana:
   image: docker.elastic.co/kibana/kibana:8.8.1

volumes:
  identityserver.mssql_volume:
  backoffice.postgresql_volume:
  backoffice.rabbitmq.1_volume:
  backoffice.rabbitmq.2_volume:
  projections.rabbitmq_volume:
  redis-master_volume:
  redis-slave_volume:
  elastic_volume:
