global using Microsoft.Extensions.Hosting;
global using Puzzle.Lib.Assistant.Enums;
global using Puzzle.Lib.Assistant.Extensions;
global using System.ComponentModel;
global using System.Globalization;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
