global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Puzzle.Lib.Social.Infrastructure;
global using Puzzle.Lib.Social.Models;
global using Puzzle.Lib.Social.Services;
global using System.Net.Http.Json;
global using System.Text.Json.Serialization;
global using static Google.Apis.Auth.GoogleJsonWebSignature;
