global using Notiflow.Backoffice.Domain.Entities.Customers;
global using Notiflow.Backoffice.Domain.Entities.Devices;
global using Notiflow.Backoffice.Domain.Entities.Histories;
global using Notiflow.Backoffice.Domain.Entities.Tenants;
global using Notiflow.Backoffice.Domain.Entities.Users;
global using Notiflow.Backoffice.Domain.Enums;
global using Puzzle.Lib.Entities.Entities.Base;
global using Puzzle.Lib.Entities.Entities.Historical;
global using Puzzle.Lib.Entities.Entities.HistoricalSoftDelete;
