global using HealthChecks.UI.Core;
global using Notiflow.Gateway;
global using Notiflow.Gateway.Infrastructure.Settings;
global using Ocelot.DependencyInjection;
global using Ocelot.Middleware;
global using Puzzle.Lib.Assistant.Extensions;
global using Puzzle.Lib.Auth;
global using Puzzle.Lib.Auth.Infrastructure;
global using Puzzle.Lib.HealthCheck;
