global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Notiflow.Lib.Database.Abstract;
global using Notiflow.Lib.Database.Infrastructure.Constants;
global using Notiflow.Lib.Database.Infrastructure.Exceptions;
global using Serilog;
global using System.Linq.Expressions;
global using System.Runtime.Serialization;
global using ILogger = Serilog.ILogger;