global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Notiflow.IdentityServer.Core.Models;
global using Notiflow.IdentityServer.Service.Auth;
global using Notiflow.IdentityServer.Service.Models;
global using Notiflow.IdentityServer.Service.Tenants;
global using Puzzle.Lib.Auth.Models;
global using Puzzle.Lib.Response.Controllers;
global using Puzzle.Lib.Response.Models;
