global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Net.Http.Headers;
global using Notiflow.Lib.Http.Services;
global using Polly;
global using Polly.Extensions.Http;
global using Serilog;
global using System.Collections.Specialized;
global using System.Net.Http.Json;
