global using Dapper;
global using MassTransit;
global using Microsoft.Extensions.Options;
global using Notiflow.Common.MessageBroker.Events;
global using Notiflow.Common.MessageBroker.Events.Notifications;
global using Notiflow.Common.Settings;
global using Notiflow.Projections.NotificationService;
global using Notiflow.Projections.NotificationService.Consumers;
global using Npgsql;
