global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.ResponseCompression;
global using Microsoft.Extensions.DependencyInjection;
global using Puzzle.Lib.Response.Models;
global using System.IO.Compression;
global using System.Net.Mime;
global using System.Text.Json.Serialization;
